# file: C:\Users\Maver\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\h11\_util.py
# hypothesis_version: 6.138.2

[400, 'LocalProtocolError', 'ProtocolError', 'RemoteProtocolError', 'Sentinel', '_T_Sentinel', 'ascii', 'bytesify', 'malformed data', 'validate']