# file: C:\Users\Maver\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\redis\connection.py
# hypothesis_version: 6.138.2

[b'\r\n', b' ', b'$', b'*', b'foo', b'proto', b'server', b'version', 6000, 6379, 65536, '*', ',', '/', '0', '2', '3', '5.3.0', '7.4.0', 'AUTH', 'CLIENT', 'Connection', 'Connection has data', 'Connection not ready', 'ConnectionInterface', 'ConnectionPool', 'F', 'FALSE', 'HELLO', 'Invalid Database', 'Invalid RESP version', 'LIB-NAME', 'LIB-VER', 'N', 'NO', 'OK', 'ON', 'PING', 'PONG', 'SELECT', 'SETINFO', 'SETNAME', 'TRACKING', 'Too many connections', 'UNKNOWN', '_CP', 'cache', 'cache_config', 'check_health', 'client_name', 'connection_class', 'db', 'decode_responses', 'default', 'encoding', 'encoding_errors', 'event_dispatcher', 'host', 'keys', 'localhost', 'max_connections', 'none', 'oid', 'optional', 'password', 'path', 'port', 'proto', 'protocol', 'redis', 'redis-py', 'redis://', 'rediss', 'rediss://', 'required', 'retry', 'retry_on_error', 'retry_on_timeout', 'server', 'socket_keepalive', 'socket_timeout', 'ssl_check_hostname', 'strict', 'timeout', 'unix', 'unix://', 'username', 'utf-8', 'version']